import supabase from './supabase';

// Get all the user details so it can be used by multiple other functions who only need a few of the details
export async function getUserDetails() {
    try {
        const { data: authUser, error: authError } = await supabase.auth.getUser();
        if (authError || !authUser?.user) {
            throw new Error('Error fetching authenticated user');
        }

        const userId = authUser.user.id;
        const { data: userDetails, error: userDetailsError } = await supabase
            .from('user_details')
            .select('firstName, lastName, email, userNote, userGoal, autoDelete, autoDeleteDays')
            .eq('uuid', userId)
            .single();

        if (userDetailsError) {
            throw new Error('Error fetching user details');
        }

        return { ...userDetails, uuid: userId };
    } catch (error) {
        console.error(error);
        return null;
    }
}

// Creates the new task with the data passed in, the taskID is auto generated by supabase
export async function insertTask(task: {
    taskCategory: string;
    taskName: string;
    uuid: string;
    dueDate: string;
}) {
    try {
        const { data, error } = await supabase.from('tasks').insert([task]).select();
        if (error) {
            return null;
        }
        return data;
    } catch (error) {
        console.error('Unexpected error inserting task:', error);
        return null;
    }
}

// Takes in a Task ID and an array of dates used for notifications. Creates a row for each Date in the array and inserts it into the task_notifications table
export async function insertNotifications(taskID: number, notificationDates: Date[]) {
    try {

        const notifications = notificationDates.map((date) => ({
            taskID: taskID,
            notificationTime: date.toISOString(),
        }));

        console.log("Notifications Payload:", notifications);

        const { data, error } = await supabase.from('task_notifications').insert(notifications).select();

        if (error) {
            console.error('Error inserting notifications:', error.message);
            return null;
        }

        return data;
    } catch (error) {
        console.error('Unexpected error inserting notifications:', error);
        return null;
    }
}

// Updates the user's note in the 'user_details' table.
// Takes uuid (user ID) and the new note string.
export const updateUserNote = async (uuid: string, newNote: string) => {
    const { data, error } = await supabase
        .from('user_details')
        .update({ userNote: newNote })
        .eq('uuid', uuid);

    if (error) {
        throw error;
    }

    return data;
};

// Updates the user's first and last name in 'user_details'.
// Takes uuid, firstName, and lastName as parameters.
export const updateUserDetails = async (uuid: string, firstName: string, lastName: string) => {
    const { data, error } = await supabase
        .from('user_details')
        .update({ firstName, lastName })
        .eq('uuid', uuid);

    if (error) {
        throw new Error(error.message);
    }

    return data;
};

// Updates the user's auto-delete toggle setting in 'user_details'.
// Takes uuid and a boolean value for autoDelete.
export const updateAutoDeleteSetting = async (uuid: string, autoDelete: boolean) => {
    const { data, error } = await supabase
        .from('user_details')
        .update({ autoDelete })
        .eq('uuid', uuid);

    if (error) {
        throw new Error(error.message);
    }

    return data;
};

// Updates the number of days for auto-deleting tasks in 'user_details'.
// Takes uuid and a number representing autoDeleteDays.
export const updateAutoDeleteDays = async (uuid: string, autoDeleteDays: number) => {
    const { data, error } = await supabase
        .from('user_details')
        .update({ autoDeleteDays })
        .eq('uuid', uuid);

    if (error) {
        throw new Error(error.message);
    }

    return data;
};

// Checks if tasks should be auto-deleted based on user settings.
// Deletes tasks and their notifications if they're past the delete threshold.
export const checkAutoDeleteTasks = async (userId: string) => {
  if (!userId) return;

  try {
    const { data: settings, error: settingsError } = await supabase
      .from('user_details')
      .select('autoDelete, autoDeleteDays')
      .eq('uuid', userId)
      .single();

    if (settingsError) {
      console.error('Error fetching user settings:', settingsError.message);
      return;
    }

    const { autoDelete, autoDeleteDays } = settings;

    if (autoDelete) {
      const { data: tasks, error: tasksError } = await supabase
        .from('tasks')
        .select('taskID, dueDate')
        .eq('uuid', userId);

      if (tasksError) {
        console.error('Error fetching tasks:', tasksError.message);
        return;
      }

      const currentDate = new Date();
      const deleteDateThreshold = new Date();
      deleteDateThreshold.setDate(currentDate.getDate() - autoDeleteDays);

      tasks.forEach(async (task) => {
        const taskDueDate = new Date(task.dueDate);

        if (taskDueDate < deleteDateThreshold) {
          // Delete related notifications
          const { error: notifDeleteError } = await supabase
            .from('task_notifications')
            .delete()
            .eq('taskID', task.taskID);

          if (notifDeleteError) {
            console.error(`Error deleting notifications for task ${task.taskID}:`, notifDeleteError.message);
            return;
          }

          // Delete the task itself
          const { error: deleteError } = await supabase
            .from('tasks')
            .delete()
            .eq('taskID', task.taskID);

          if (deleteError) {
            console.error(`Error deleting task ${task.taskID}:`, deleteError.message);
          }
        }
      });
    }
  } catch (error) {
    console.error('Error checking auto-delete tasks:', error);
  }
};

// Fetches all tasks from the 'tasks' table associated with a specific user.
// Takes uuid and returns a list of that user's tasks.
export async function getTasksByUUID(uuid: string) {
  try {
      const { data, error } = await supabase
          .from("tasks")
          .select("taskID, taskCategory, taskName, dueDate, completed")
          .eq("uuid", uuid);

      if (error) {
          throw new Error(error.message);
      }

      return data;
  } catch (error) {
      console.error("Error fetching tasks:", error);
      return [];
  }
}

// Updates the user's goal in the 'user_details' table.
// Takes uuid and the goal string (or null to clear it).
export const updateUserGoal = async (uuid: string, goal: string | null) => {
  try {
      const { data, error } = await supabase
          .from('user_details')
          .update({ userGoal: goal })
          .eq('uuid', uuid);

      if (error) {
          console.error("Error updating user goal:", error.message);
          return null;
      }
      return data;
  } catch (error) {
      console.error("Error updating user goal:", error);
      return null;
  }
};

// Retrieves only the incomplete tasks for a specific user from 'tasks'.
// Takes uuid and returns tasks where completed is false.
export const getIncompleteTasks = async (uuid: string) => {
  try {
      const { data, error } = await supabase
          .from("tasks")
          .select("taskID, taskCategory, taskName, dueDate")
          .eq("uuid", uuid)
          .eq("completed", false);

      if (error) {
          console.error("Error fetching incomplete tasks:", error.message);
          return [];
      }

      return data.sort(
          (a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime()
      );
  } catch (error) {
      console.error("Unexpected error fetching tasks:", error);
      return [];
  }
};

// Fetches a single task by its taskID from 'tasks' table.
// Takes taskId and returns the task details.
export const fetchTaskById = async (taskId: string) => {
  const { data, error } = await supabase
    .from('tasks')
    .select('taskID, taskCategory, taskName, dueDate, completed')
    .eq('taskID', taskId)
    .single();

  if (error) throw error;
  return data;
};

// Fetches notifications associated with a given taskID.
// Takes taskId and returns a list of related notifications.
export const fetchTaskNotifications = async (taskId: string) => {
  const { data, error } = await supabase
    .from('task_notifications')
    .select('notificationID, notificationTime, taskID')
    .eq('taskID', taskId);

  if (error) throw error;
  return data;
};

// Updates a task in the 'tasks' table by its taskID.
// Takes taskId and an object with updated task fields.
export const updateTaskById = async (taskId: string, updatedTask: any) => {
  const { error } = await supabase
    .from('tasks')
    .update(updatedTask)
    .eq('taskID', taskId);

  if (error) throw error;
};

// Updates the notification times for a list of notifications based on a time difference.
// Takes an array of notifications and a time difference in milliseconds.
export const updateTaskNotifications = async (
  notifications: any[],
  timeDifference: number
) => {
  for (const notification of notifications) {
    const oldNotificationTime = new Date(notification.notificationTime);
    const updatedNotifyTime = new Date(oldNotificationTime.getTime() + timeDifference);

    const { error } = await supabase
      .from('task_notifications')
      .update({ notificationTime: updatedNotifyTime.toISOString() })
      .eq('notificationID', notification.notificationID);

    if (error) throw error;
  }
};

// Deletes a task and all its associated notifications from the database.
// Takes taskId and performs both deletions.
export const deleteTaskAndNotifications = async (taskId: string) => {
  const { error: notificationError } = await supabase
    .from('task_notifications')
    .delete()
    .eq('taskID', taskId);
  if (notificationError) throw notificationError;

  const { error: taskError } = await supabase
    .from('tasks')
    .delete()
    .eq('taskID', taskId);
  if (taskError) throw taskError;
};
